runtime: python38
entrypoint: gunicorn -b :$PORT application.main:server
service: oidc-flask-template

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: auto
